### ISSUE TITLE
`backy check` and `backy status` appear to output different time zones

### ISSUE THREAD

**Issue by osnyx** [flyingcircusio/backy#66]
seen in backy-2.5.1dev0:

`backy check`:

`2024-05-29T19:36:56.303331 1924551 C redacted00               daemon/check-sla-violation     last_time='2024-05-28 04:47:54.749521+00:00'`

`backy status`:

`| 2024-05-28 06:47:54  | 5NS6ovFuGEupcjEBB5uzBQ |  5.3 GiB | 8 hours  | daily        | trusted |`

**Comment by ctheune** [comment]
backy check is a machine interface primarily. as long as timezones are marked up (the table in status shows Europe/Berlin; the check shows +00:00) i'm fine with it being different.

**Comment by osnyx** [comment]
For `backy status`, the timezone is indeed *not* marked up, see output above.

**Comment by osnyx** [comment]
Ah, sorry then, that works for me as well.
